version: '3.2'

services:
   db:
      image: mysql:8.0
      container_name: mysql
      restart: always
      ports:
       - '3306:3306'
      volumes:
       - D:/server/mysql/db:/var/lib/mysql
      environment:
         MYSQL_ROOT_USER: root
         MYSQL_ROOT_PASSWORD: root
         TZ: Asia/Bangkok
         # MYSQL_DATABASE: shop
         # MYSQL_USER: root
         # MYSQL_PASSWORD: secret

   app:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
       - '80:80'
      environment:
        PMA_HOST: db