server:
    port: 8080
    error:
        include-message: always

cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "*"

spring:
    datasource:
        url: 'jdbc:mysql://localhost:3306/spring'
        username: root
        password: root
        driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
#        hibernate:
#            ddl-auto: create
#        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
jwt:
    signingKey: ZLQITRG6188MGBLZ6RRMA7JJDKCNNO9Q127DF1V8HXGD2R8V5J9GB5XB3K79FPMI
    issuer: Today
    tokenExpInSecs: 3600
    refreshTokenExpInSecs: 7200
